const express = require('express');
const router = express.Router();
const db = require('../db/database');
const { optionalToken } = require('../middleware/auth');
const { computeScores, healthLabel, buildBlueprint, generateBusinessAnalytics } = require('../scoring');

/**
 * POST /api/assessments
 * Process, score, analyze, and save Health Check answers
 */
router.post('/', optionalToken, (req, res) => {
  try {
    const { businessId, businessData, answers } = req.body;

    if (!answers || typeof answers !== 'object') {
      return res.status(400).json({ success: false, message: 'Answers object is required.' });
    }

    let targetBizId = businessId;
    let bType = 'Retail Store';
    let bName = 'Client Business';

    // If business doesn't exist yet, create one
    if (!targetBizId && businessData) {
      const { name, owner, type, years } = businessData;
      let userId = req.user ? req.user.id : null;
      bType = type || 'Other';
      bName = name || 'New Client Business';

      const insertBiz = db.prepare(`
        INSERT INTO businesses (user_id, name, owner_name, business_type, years_operating, membership_plan, assigned_consultant)
        VALUES (?, ?, ?, ?, ?, 'Basic', 'Dr. Aris Thorne (SYNEX)')
      `);
      const result = insertBiz.run(userId, bName, owner || 'Business Owner', bType, years || '1–3 years');
      targetBizId = result.lastInsertRowid;

      // Seed onboarding tasks
      const DEFAULT_ONBOARD_TASKS = [
        { key: 'f1', day: 'Day 1–5 · Foundation Setup', text: 'Complete Google Business Profile' },
        { key: 'f2', day: 'Day 1–5 · Foundation Setup', text: 'Define target customer' },
        { key: 'f3', day: 'Day 6–15 · Analysis & Strategy', text: 'Review current marketing' },
        { key: 'f4', day: 'Day 6–15 · Analysis & Strategy', text: 'Set up lead tracking' },
        { key: 'f5', day: 'Day 16–30 · Implementation', text: 'Create first growth campaign' },
      ];
      const insertTask = db.prepare(`
        INSERT INTO onboarding_tasks (business_id, task_key, phase_group, text, is_completed)
        VALUES (?, ?, ?, ?, 0)
      `);
      DEFAULT_ONBOARD_TASKS.forEach(t => insertTask.run(targetBizId, t.key, t.day, t.text));

      // Seed growth cycle
      db.prepare(`
        INSERT INTO growth_cycles (business_id, cycle_stage, stage_name, notes)
        VALUES (?, 0, 'Collect Data', 'Initial business assessment recorded.')
      `).run(targetBizId);
    } else if (targetBizId) {
      const existing = db.prepare('SELECT name, business_type FROM businesses WHERE id = ?').get(targetBizId);
      if (existing) {
        bName = existing.name;
        bType = existing.business_type;
      }
    }

    if (!targetBizId) {
      return res.status(400).json({ success: false, message: 'Business ID or Business Data is required.' });
    }

    // 1. Compute Scores
    const { overall, catScores } = computeScores(answers);
    const health = healthLabel(overall);

    // 2. Save Assessment
    const insertAssessment = db.prepare(`
      INSERT INTO assessments (business_id, overall_score, category_scores, answers)
      VALUES (?, ?, ?, ?)
    `);
    const assessRes = insertAssessment.run(
      targetBizId,
      overall,
      JSON.stringify(catScores),
      JSON.stringify(answers)
    );
    const assessmentId = assessRes.lastInsertRowid;

    // 3. Build & Upsert Blueprint
    const blueprintData = buildBlueprint(catScores);
    const existingBlueprint = db.prepare('SELECT id FROM blueprints WHERE business_id = ?').get(targetBizId);

    if (existingBlueprint) {
      db.prepare(`
        UPDATE blueprints
        SET assessment_id = ?, priorities = ?, updated_at = CURRENT_TIMESTAMP
        WHERE business_id = ?
      `).run(assessmentId, JSON.stringify(blueprintData.priorities), targetBizId);
    } else {
      db.prepare(`
        INSERT INTO blueprints (business_id, assessment_id, priorities, roadmap_phase, notes)
        VALUES (?, ?, ?, 1, 'Custom Growth Blueprint generated by SYNEX Framework')
      `).run(targetBizId, assessmentId, JSON.stringify(blueprintData.priorities));
    }

    // 4. Generate Business Analytics
    const analytics = generateBusinessAnalytics(catScores, bType, bName);
    const business = db.prepare('SELECT * FROM businesses WHERE id = ?').get(targetBizId);

    res.json({
      success: true,
      message: 'Business Health Check completed successfully.',
      businessId: targetBizId,
      assessmentId,
      overall,
      catScores,
      health: health.label,
      healthCls: health.cls,
      blueprint: blueprintData,
      analytics,
      business,
    });
  } catch (err) {
    console.error('Assessment submission error:', err);
    res.status(500).json({ success: false, message: 'Server error processing assessment.' });
  }
});

/**
 * GET /api/assessments/latest/:businessId
 * Retrieve the latest assessment & analytics for a given business
 */
router.get('/latest/:businessId', (req, res) => {
  try {
    const bizId = req.params.businessId;
    const business = db.prepare('SELECT * FROM businesses WHERE id = ?').get(bizId);

    if (!business) {
      return res.status(404).json({ success: false, message: 'Business not found.' });
    }

    const assessment = db.prepare(`
      SELECT * FROM assessments WHERE business_id = ? ORDER BY created_at DESC LIMIT 1
    `).get(bizId);

    if (!assessment) {
      return res.status(404).json({ success: false, message: 'No assessment found for this business.' });
    }

    const parsedScores = JSON.parse(assessment.category_scores);
    const health = healthLabel(assessment.overall_score);
    const blueprint = db.prepare('SELECT * FROM blueprints WHERE business_id = ?').get(bizId);
    const analytics = generateBusinessAnalytics(parsedScores, business.business_type, business.name);

    res.json({
      success: true,
      assessment: {
        id: assessment.id,
        businessId: assessment.business_id,
        overall: assessment.overall_score,
        catScores: parsedScores,
        health: health.label,
        healthCls: health.cls,
        createdAt: assessment.created_at,
      },
      blueprint: blueprint ? { ...blueprint, priorities: JSON.parse(blueprint.priorities) } : null,
      analytics,
    });
  } catch (err) {
    console.error('Get latest assessment error:', err);
    res.status(500).json({ success: false, message: 'Server error retrieving assessment.' });
  }
});

module.exports = router;
